version: "3.2"

services:
  raks:
    image: node:14
    # image: mcr.microsoft.com/playwright:bionic
    working_dir: /home
    volumes:
      - ./index.mjs:/home/index.mjs
      - ./package.json:/home/package.json
      - ./package-lock.json:/home/package-lock.json
      - ./out:/home/out
    environment:
      - PAGEURL
      - USERINFO
      - LOGIN_SELECTER
    # bash -c "pwd && ls -la && wc -l index.mjs"
    command: >
      bash -c "whoami && npm i && npm start"
